//dance
let songs = [
    "<a href=https://www.youtube.com/watch?v=dQw4w9WgXcQ target=_blank> Rick Astley - Never Gonna Give You Up </a><br> duration: 3:33<br><i>get rickrolled</i> <br><br> <audio controls autoplay> <source src=resources/music/dance/NeverGonnaGiveYouUp.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=GOA7ZXVGOtc target=_blank> Ionut Cercel - Made in Romania </a><br> duration: 4:05<br><i>for the memesss</i> <br><br> <audio controls> <source src=resources/music/dance/MadeinRomania.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=TADxdahPBUA target=_blank> Ace Of Base - Happy Nation </a><br> duration: 4:15<br><i>war thunder theme, lol</i> <br><br> <audio controls> <source src=resources/music/dance/HappyNation.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=c1ZCYY-4lAM target=_blank> Modern Talking - Cheri Cheri Lady </a><br> duration: 3:46<br><i>love this song</i> <br><br> <audio controls> <source src=resources/music/dance/CheriCheriLady.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=OFNrN_6Ta5I target=_blank> Haddaway - What is Love </a><br> duration: 4:30<br> <br><br> <audio controls> <source src=resources/music/dance/WhatisLove.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=6JnGBs88sL0 target=_blank> Nelly Furtado - Say It Right </a><br> duration: 3:43<br> <br><br> <audio controls> <source src=resources/music/dance/SayItRight.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=Ju7_j6UtlQ0 target=_blank> Timbaland - Give It To Me </a><br> duration: 3:54<br> <br><br> <audio controls> <source src=resources/music/dance/GiveItToMe.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=gUbeQ7eb3nc target=_blank> Stromae - Alors on danse </a><br> duration: 3:26<br><i>love the melody</i> <br><br> <audio controls> <source src=resources/music/dance/Alorsondanse.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=Ck0LO6b6OQc target=_blank> Alice Deejay - Better Off Alone </a><br> duration: 3:38<br> <br><br> <audio controls> <source src=resources/music/dance/BetterOffAlone.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=MR3uP7IYz44 target=_blank> Modjo - Lady (Hear Me Tonight) </a><br> duration: 5:07<br><i>a legendary one</i> <br><br> <audio controls> <source src=resources/music/dance/Lady(HearMeTonight).mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=MxUArvDcCi8 target=_blank> Cutting Crew - (I Just) Died In Your Arms </a><br> duration: 4:40<br>(this song is golden) <br><br> <audio controls> <source src=resources/music/dance/(IJust)DiedInYourArms.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=NqThf-MpCjs target=_blank> Crystal Waters - Gypsy Woman </a><br> duration: 7:31<br> <br><br> <audio controls> <source src=resources/music/dance/GypsyWoman.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=9hYNjn1gohM target=_blank> Crazy Town - Butterfly </a><br> duration: 3:36<br> <br><br> <audio controls> <source src=resources/music/dance/Butterfly.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=B4yVmBdXwfw target=_blank> The Romantics - Talking In Your Sleep </a><br> duration: 3:56<br> <br><br> <audio controls> <source src=resources/music/dance/TalkingInYourSleep.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=rsf_gTZG4cI target=_blank> Redbone - Come and Get Your Love </a><br> duration: 3:25<br> <br><br> <audio controls> <source src=resources/music/dance/ComeandGetYourLove.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=Ye9hGotPPVk target=_blank> Elton John - I'm Still Standing </a><br> duration: 3:03<br> <br><br> <audio controls> <source src=resources/music/dance/I'mStillStanding.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=4USMXubaAmc target=_blank> Modern Talking - You're My Heart, You're My Soul </a><br> duration: 5:32<br> <br><br> <audio controls> <source src=resources/music/dance/You'reMyHeart,You'reMySoul.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=ViP87WipSm0 target=_blank> La Bouche - Be My Lover </a><br> duration: 4:01<br> <br><br> <audio controls> <source src=resources/music/dance/BeMyLover.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=b9McVO9hpUE target=_blank> La Bouche - Sweet dreams </a><br> duration: 3:24<br> <br><br> <audio controls> <source src=resources/music/dance/Sweetdreams.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=BcPMNG6sUN8 target=_blank> Modern Talking - Let's Talk About Love </a><br> duration: 3:54<br> <br><br> <audio controls> <source src=resources/music/dance/Let'sTalkAboutLove.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=Lp2qcCrdBLA target=_blank> Modern Talking - Brother Louie </a><br> duration: 3:41<br> <br><br> <audio controls> <source src=resources/music/dance/BrotherLouie.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=qDQvH0YXONg target=_blank> Modern Talking - Geronimo's Cadillac </a><br> duration: 3:18<br> <br><br> <audio controls> <source src=resources/music/dance/Geronimo'sCadillac.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=6VCsABl390Y target=_blank> Corona - The Rhythm of the Night </a><br> duration: 4:24<br> <br><br> <audio controls> <source src=resources/music/dance/TheRhythmoftheNight.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=ghGiv7YLC7Q target=_blank> Boney M. - Sunny </a><br> duration: 4:01<br> <br><br> <audio controls> <source src=resources/music/dance/Sunny.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=f3XcNskAxp0 target=_blank> Boney M. - Ma Baker </a><br> duration: 4:36<br> <br><br> <audio controls> <source src=resources/music/dance/MaBaker.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=6JhVo2zS8hU target=_blank> Boney M. - Rasputin </a><br> duration: 4:29<br> <br><br> <audio controls> <source src=resources/music/dance/Rasputin.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=JWay7CDEyAI target=_blank> ABBA - Gimme! Gimme! Gimme! (A Man After Midnight) </a><br> duration: 4:52<br> <br><br> <audio controls> <source src=resources/music/dance/Gimme!Gimme!Gimme!(AManAfterMidnight).mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=6GCNUeTFSbA target=_blank> Michael Sembello - Maniac </a><br> duration: 4:04<br> <br><br> <audio controls> <source src=resources/music/dance/Maniac.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=5mHzaIehRTE target=_blank> ABBA - Lay All Your Love On Me </a><br> duration: 4:34<br> <br><br> <audio controls> <source src=resources/music/dance/LayAllYourLoveOnMe.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=1LPNuFkteI8 target=_blank> ABBA - Money, Money, Money </a><br> duration: 3:06<br> <br><br> <audio controls> <source src=resources/music/dance/Money,Money,Money.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=_Jl-QpJNKiQ target=_blank> Mr. President - Coco Jamboo </a><br> duration: 3:38<br> <br><br> <audio controls> <source src=resources/music/dance/CocoJamboo.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=mRNcPbCJNJ8 target=_blank> Sade - Smooth Operator </a><br> duration: 4:18<br> <br><br> <audio controls> <source src=resources/music/dance/SmoothOperator.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=3cKtSlsYVEU target=_blank> Earth Wind & Fire - September </a><br> duration: 3:35<br> <br><br> <audio controls> <source src=resources/music/dance/September.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=z2qoihbzc3E target=_blank> Bee Gees - Stayin Alive </a><br> duration: 4:43<br> <br><br> <audio controls> <source src=resources/music/dance/StayinAlive.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=50ObRkB7xHI target=_blank> Boney M. - Daddy Cool </a><br> duration: 3:28<br> <br><br> <audio controls> <source src=resources/music/dance/DaddyCool.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=84sHTvn6xf8 target=_blank> Cascada - Everytime We Touch </a><br> duration: 3:17<br> <br><br> <audio controls> <source src=resources/music/dance/EverytimeWeTouch.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=AvHH_u8c3Qw target=_blank> Des'ree - Life </a><br> duration: 3:36<br> <br><br> <audio controls> <source src=resources/music/dance/Life.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=9cKEUmLIhhI target=_blank> Londonbeat - I've Been Thinking About You </a><br> duration: 3:50<br> <br><br> <audio controls> <source src=resources/music/dance/I'veBeenThinkingAboutYou.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=MOpmCZ904j0 target=_blank> Tomcraft - Sureshot </a><br> duration: 3:08<br> <br><br> <audio controls> <source src=resources/music/dance/Sureshot.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=EAwWPadFsOA target=_blank> The Immortals - Techno Syndrome </a><br> duration: 3:25<br><i>W song, W games</i> <br><br> <audio controls> <source src=resources/music/dance/TechnoSyndrome.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>"
];

function displayRandomSong() {
    const random = Math.floor(Math.random() * songs.length);
    document.getElementById('song-container').innerHTML = songs[random];
}

displayRandomSong();

document.getElementById('new-song-btn').addEventListener('click', displayRandomSong);