// rock
let songs = [
    "<a href=https://www.youtube.com/watch?v=isCh4kCeNYU target=_blank> Guns N' Roses - Civil War </a><br> duration: 7:42<br> <br><br> <audio controls> <source src=resources/music/rock/CivilWar.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
    "<a href=https://www.youtube.com/watch?v=T0ZmErXkbxE target=_blank> Guns N' Roses - Paradise City </a><br> duration: 6:45<br> <br><br> <audio controls> <source src=resources/music/rock/ParadiseCity.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
    "<a href=https://www.youtube.com/watch?v=oMfMUfgjiLg target=_blank> Guns N' Roses - Sweet Child O' Mine </a><br> duration: 5:56<br> <br><br> <audio controls> <source src=resources/music/rock/SweetChildO'Mine.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
    "<a href=https://www.youtube.com/watch?v=tAGnKpE4NCI target=_blank> Metallica - Nothing Else Matters </a><br> duration: 6:25<br><i>in my top 5 favorites</i> <br><br> <audio controls> <source src=resources/music/rock/NothingElseMatters.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=WnJFQEHsSrU target=_blank> Scorpions - Rock You Like a Hurricane </a><br> duration: 4:13<br> <br><br> <audio controls> <source src=resources/music/rock/RockYouLikeaHurricane.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=qabmngqxPtc target=_blank> Manowar - Heart of Steel </a><br> duration: 5:10<br><i>stand and fight!</i> <br><br> <audio controls> <source src=resources/music/rock/HeartofSteel.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=AepjLbcLrJE target=_blank> Scorpions - Always Somewhere </a><br> duration: 4:57<br> <br><br> <audio controls> <source src=resources/music/rock/AlwaysSomewhere.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=BciS5krYL80 target=_blank> Eagles - Hotel California </a><br> duration: 6:31<br><i>love this song</i> <br><br> <audio controls> <source src=resources/music/rock/HotelCalifornia.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=5nULVceKyG0 target=_blank> Scorpions - Still Loving You </a><br> duration: 6:28<br><i>Scorpions's ballands are too good</i> <br><br> <audio controls> <source src=resources/music/rock/StillLovingYou.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=-DPomaw9Sl0 target=_blank> Guns N' Roses - Don't Cry </a><br> duration: 4:33<br> <br><br> <audio controls> <source src=resources/music/rock/Don'tCry.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=o3y7cFR7uTg target=_blank> Scorpions - Send Me An Angel </a><br> duration: 4:33<br><i>here I ammm</i> <br><br> <audio controls> <source src=resources/music/rock/SendMeAnAngel.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=qalokUhzzA4 target=_blank> Deep Purple - Perfect Strangers </a><br> duration: 5:28<br> <br><br> <audio controls> <source src=resources/music/rock/PerfectStrangers.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=8SbUC-UaAxE target=_blank> Guns N' Roses - November Rain </a><br> duration: 8:56<br><i>what a beautiful song</i> <br><br> <audio controls> <source src=resources/music/rock/NovemberRain.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=NvR60Wg9R7Q target=_blank> Bon Jovi - Bed Of Roses </a><br> duration: 6:34<br><i>no words can describe how good this song is</i> <br><br> <audio controls> <source src=resources/music/rock/BedOfRoses.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=KgP49KGSDSs target=_blank> Bon Jovi - Wanted Dead Or Alive </a><br> duration: 5:08<br> <br><br> <audio controls> <source src=resources/music/rock/WantedDeadOrAlive.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=p__81XMLRvA target=_blank> Bon Jovi - Always </a><br> duration: 5:53<br> <br><br> <audio controls> <source src=resources/music/rock/Always.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=nukP7I7uwqo target=_blank> Bon Jovi - You Give Love A Bad Name </a><br> duration: 3:42<br> <br><br> <audio controls> <source src=resources/music/rock/YouGiveLoveABadName.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=iDsqNYh_KQ4 target=_blank> Bon Jovi - I'll Be There For You </a><br> duration: 5:46<br> <br><br> <audio controls> <source src=resources/music/rock/I'llBeThereForYou.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=ICJs1CxCRt0 target=_blank> Steelheart - She's Gone </a><br> duration: 6:32<br> <br><br> <audio controls> <source src=resources/music/rock/She'sGone.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=bXJ5bZ8hq34 target=_blank> Opeth - Soldier of Fortune </a><br> duration: 3:28<br><i>this cover's too good</i> <br><br> <audio controls> <source src=resources/music/rock/SoldierofFortune(Opeth).mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=znW-P7lMKjU target=_blank> Deep Purple - Soldier Of Fortune </a><br> duration: 3:24<br> <br><br> <audio controls> <source src=resources/music/rock/SoldierOfFortune(DeepPurple).mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=bO28lB1uwp4 target=_blank> Creedence Clearwater Revival - Have You Ever Seen The Rain </a><br> duration: 2:40<br> <br><br> <audio controls> <source src=resources/music/rock/HaveYouEverSeenTheRain.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=vOn0z0IRVN8 target=_blank> Nazareth - Love Hurts </a><br> duration: 3:53<br> <br><br> <audio controls> <source src=resources/music/rock/LoveHurts.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=rXAj7b3B_14 target=_blank> Def Leppard - Two Steps Behind </a><br> duration: 4:17<br> <br><br> <audio controls> <source src=resources/music/rock/TwoStepsBehind.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=1Cw1ng75KP0 target=_blank> Heart - Alone </a><br> duration: 3:38<br> <br><br> <audio controls> <source src=resources/music/rock/Alone.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=Us3cGQs0Q8A target=_blank> Aerosmith - I Don't Want to Miss a Thing </a><br> duration: 4:58<br> <br><br> <audio controls> <source src=resources/music/rock/IDon'tWanttoMissaThing.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=6Ejga4kJUts target=_blank> The Cranberries - Zombie </a><br> duration: 5:06<br> <br><br> <audio controls> <source src=resources/music/rock/Zombie.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=m7nwbJLO9qo target=_blank> Black Sabbath - Paranoid </a><br> duration: 2:47<br> <br><br> <audio controls> <source src=resources/music/rock/Paranoid.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=NNiTxUEnmKI target=_blank> Europe - The Final Countdown </a><br> duration: 5:10<br><i>o ma gad</i> <br><br> <audio controls> <source src=resources/music/rock/TheFinalCountdown.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=lDK9QqIzhwk target=_blank> Bon Jovi - Livin' On A Prayer </a><br> duration: 4:09<br> <br><br> <audio controls> <source src=resources/music/rock/Livin'OnAPrayer.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=ljUtuoFt-8c target=_blank> Nirvana - Smells Like Teen Spirit </a><br> duration: 5:01<br><i>Nirvana good</i> <br><br> <audio controls> <source src=resources/music/rock/SmellsLikeTeenSpirit.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=ZEMBDKMtHqM target=_blank> Nirvana - Come As You Are </a><br> duration: 3:38<br> <br><br> <audio controls> <source src=resources/music/rock/ComeAsYouAre.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=JtWaCViY_tc target=_blank> Nirvana - Rape Me </a><br> duration: 2:50<br><i>that's a name</i> <br><br> <audio controls> <source src=resources/music/rock/RapeMe.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=E6SbPv1Fu80 target=_blank> Nirvana - In Bloom </a><br> duration: 4:15<br> <br><br> <audio controls> <source src=resources/music/rock/InBloom.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=Dx1SPxGn-iU target=_blank> Green Day - Boulevard of Broken Dreams </a><br> duration: 4:21<br><i>love this song</i> <br><br> <audio controls> <source src=resources/music/rock/BoulevardofBrokenDreams.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=d9jhDwxt22Y target=_blank> Joan Jett - I Love Rock 'N Roll </a><br> duration: 2:55<br><i>same, same</i> <br><br> <audio controls> <source src=resources/music/rock/ILoveRock'NRoll.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=x6fB8KMUnz0 target=_blank> Joan Jett - Bad Reputation </a><br> duration: 2:49<br> <br><br> <audio controls> <source src=resources/music/rock/BadReputation.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=x-xTttimcNk target=_blank> Pink Floyd - Comfortably Numb </a><br> duration: 6:22<br> <br><br> <audio controls> <source src=resources/music/rock/ComfortablyNumb.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=LTseTg48568 target=_blank> Pink Floyd - Comfortably Numb (Live) </a><br> duration: 9:59<br><i>the extended solo, omg</i> <br><br> <audio controls> <source src=resources/music/rock/ComfortablyNumb(Live).mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=ZP69PLBqFUo target=_blank> TOTO - Hold the Line </a><br> duration: 3:55<br> <br><br> <audio controls> <source src=resources/music/rock/HoldtheLine.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=QAo_Ycocl1E target=_blank> TOTO - Africa </a><br> duration: 4:55<br> <br><br> <audio controls> <source src=resources/music/rock/Africa.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=OMOGaugKpzs target=_blank> The Police - Every Breath You Take </a><br> duration: 4:13<br> <br><br> <audio controls> <source src=resources/music/rock/EveryBreathYouTake.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=4IMppxFcnpc target=_blank> a-ha - Crying in the Rain </a><br> duration: 4:22<br> <br><br> <audio controls> <source src=resources/music/rock/CryingintheRain.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=8VgRL8Htv7k target=_blank> Guns N' Roses - Estranged </a><br> duration: 9:23<br> <br><br> <audio controls> <source src=resources/music/rock/Estranged.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=UjWZGLi-1jM target=_blank> 3 Doors Down - Kryptonite </a><br> duration: 3:53<br> <br><br> <audio controls> <source src=resources/music/rock/Kryptonite.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=0FIZsxAjtwo target=_blank> Twisted Sister - I Wanna Rock </a><br> duration: 2:59<br> <br><br> <audio controls> <source src=resources/music/rock/IWannaRock.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=ZqOp76R12DM target=_blank> Twisted Sister - We're Not Gonna Take It </a><br> duration: 3:39<br> <br><br> <audio controls> <source src=resources/music/rock/We'reNotGonnaTakeIt.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=D_QLxj8jCF0 target=_blank> The White Stripes - Seven Nation Army </a><br> duration: 3:52<br> <br><br> <audio controls> <source src=resources/music/rock/SevenNationArmy.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=067r16_aGr4 target=_blank> Survivor Band - Eye of the Tiger </a><br> duration: 4:05<br> <br><br> <audio controls> <source src=resources/music/rock/EyeoftheTiger.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=1L3XxUxEb6U target=_blank> Deep Purple - Smoke On The Water </a><br> duration: 5:37<br> <br><br> <audio controls> <source src=resources/music/rock/SmokeOnTheWater.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=hQ_Z-10dXSE target=_blank> Ozzy Osbourne - Crazy Train </a><br> duration: 4:53<br> <br><br> <audio controls> <source src=resources/music/rock/CrazyTrain.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>",
	"<a href=https://www.youtube.com/watch?v=7XyHOdMvHg0 target=_blank> Dio - Rainbow In The Dark </a><br> duration: 4:14<br><i>love this song</i> <br><br> <audio controls> <source src=resources/music/rock/RainbowInTheDark.mp3 type=audio/mpeg> Oof! Seems like your browser doesn't support the audio element </audio>"
];

function displayRandomSong() {
    const random = Math.floor(Math.random() * songs.length);
    document.getElementById('song-container').innerHTML = songs[random];
}

displayRandomSong();

document.getElementById('new-song-btn').addEventListener('click', displayRandomSong);